Practice Project/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustomerPriority__c</fullName>
        <label>Customer Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NumberofLocations__c</fullName>
        <label>Number of Locations</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLAExpirationDate__c</fullName>
        <label>SLA Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platinum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UpsellOpportunity__c</fullName>
        <label>Upsell Opportunity</label>
        <picklist>
            <picklistValues>
                <fullName>Maybe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Practice Project/src/classes/nestedqueryexample.cls
public with sharing class nestedqueryexample 
{
	public  List<Contact> contacts{get;set;}
	 public List<Account> getaccsandtmember()
	  {
	  	Set<Id> setAccountId = new Set<Id>();
	     List<Account> accounts = [Select a.Website, a.UpsellOpportunity__c, a.Type, a.TickerSymbol, a.SystemModstamp, a.Site, a.Sic, a.ShippingStreet, a.ShippingState, a.ShippingPostalCode, a.ShippingCountry, a.ShippingCity, a.SLA__c, a.SLASerialNumber__c, a.SLAExpirationDate__c, a.Rating, a.Phone, a.ParentId, a.Ownership, a.OwnerId, a.NumberofLocations__c, a.NumberOfEmployees, a.Name, a.MasterRecordId, a.LastModifiedDate, a.LastModifiedById, a.LastActivityDate, a.IsDeleted, a.Industry, a.Id, a.Fax, a.Description, a.CustomerPriority__c, a.CreatedDate, a.CreatedById, a.BillingStreet, a.BillingState, a.BillingPostalCode, a.BillingCountry, a.BillingCity, a.AnnualRevenue, a.Active__c, a.AccountNumber From Account a];
	     for(Account objAcc : accounts)
	     {
	     	setAccountId.add(objAcc.Id);
	     }
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getLimitQueries());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getAggregateQueries());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getCallouts());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getChildRelationshipsDescribes());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getCpuTime());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getDmlRows());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getDmlStatements());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getEmailInvocations());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getFieldsDescribes());
	     Error.DebugLog('=======Limit of Query ==== '+Limits.getFindSimilarCalls());
	     contacts = [Select c.LastName, c.FirstName, c.AssistantName, c.AccountId From Contact c Where c.AccountId =: setAccountId];
	     return accounts;
	  }
}