Practice Project/src/objects/CustomerPortal__c.object
<CustomObject>
    <description>This is the CustomerPortal User object</description>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CustomerPortal</label>
    <nameField>
        <label>CustomerPortal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomerPortal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Practice Project/src/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>CustomerPortal__c</fullName>
        <label>CustomerPortal</label>
        <referenceTo>CustomerPortal__c</referenceTo>
        <relationshipLabel>Patient</relationshipLabel>
        <relationshipName>Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Practice Project/src/classes/IndexController.cls
public with sharing class IndexController{
	
	public CustomerPortal__c objPortalUser{get;set;}
	
	public List<Patient__c> lstPatient{get;set;}
	
	public IndexController(){
		// UserName Password URL
		objPortalUser = new CustomerPortal__c();
		lstPatient = new List<Patient__c>();
	}
	
	public Pagereference Init(){
		Error.DebugLog('startUrl ===========>'+Site.getPrefix());
		Pagereference page = site.login('niket.c2009@gmail.com.dev', 'neha@123','/home/home.jsp');
		System.debug('Current User ==>'+Userinfo.getSessionId());
		Error.DebugLog('Session Id ===========>'+Userinfo.getSessionId());
		Error.DebugLog('Name ===========>'+Userinfo.getName());
		Error.DebugLog('profile ===========>'+Userinfo.getProfileId());
		return null;
	}
	
	public Pagereference login(){
		if(objPortalUser.Name != null && objPortalUser.Password__c != null){
			lstPatient = [Select Id,Name from Patient__c where CustomerPortal__r.Name =:objPortalUser.Name];
			Error.DebugLog('lstPatient '+lstPatient);
		}
		return null;
	}
}